import { useEffect, useRef, useState } from "react";
import { gsap } from "gsap";
import { Pencil, Copy, Trash2, Share2, Plus } from "lucide-react";
import ManifestTable, { ManifestSkeleton } from "../components/ManifestTable";
import ContainerInfoOverlay from "../components/ContainerInfoOverlay";
import ExportMenu from "../components/ExportMenu";
import DocumentGenerateMenu from "../components/documents/DocumentGenerateMenu";
import CreateVoyageModal from "../components/CreateVoyageModal";
import ConfirmDialog from "../components/ConfirmDialog";
import VoyagePnlStrip from "../components/expenses/VoyagePnlStrip";
import BookingsView from "./BookingsView";
import DocumentsView from "./DocumentsView";
import ActivityFeedView from "./ActivityFeedView";
import ExpenseListView from "./expenses/ExpenseListView";
import { fetchExpensesByVoyage, fromDbExpense } from "../lib/db";
import { useRouter } from "../context/RouterContext";
import { recordEntityVisit } from "../lib/recentEntities";
import { useToast } from "../components/Toast";
import {
  voyageStats,
  VOYAGE_STATUS_COLORS,
  VOYAGE_STATUS_CYCLE,
} from "../data/statusHelpers";
import { theme } from "../theme";

const iconBtn = {
  background: theme.color.surface,
  border: `1px solid ${theme.color.borderStrong}`,
  color: theme.color.inkSoft,
  borderRadius: theme.radius.input,
  padding: "7px 9px",
  cursor: "pointer",
  display: "flex",
  alignItems: "center",
  gap: 6,
  fontFamily: theme.font.mono,
  fontSize: 11,
};

function buildShareText(voyage) {
  const s = voyageStats(voyage);
  const lines = (voyage.containers || [])
    .map((c, i) => {
      const bags = (c.lines || []).reduce((a, l) => a + Number(l.qty || 0), 0);
      const cargo = [...new Set((c.lines || []).map((l) => l.cargo))].join(", ") || "empty";
      return `${i + 1}. ${c.number || "—"} — ${cargo} (${bags} bags) — ${
        c.sealed ? "SEALED" : "open"
      }`;
    })
    .join("\n");
  return `*VOYAGE SUMMARY — ${voyage.voyageNo}*
Vessel: ${voyage.vessel}
Date: ${voyage.date}
Route: ${voyage.pol} → ${voyage.pod}

*Containers: ${s.total}* (${s.sealed} sealed)
*Total Cargo: ${s.bags} bags / ${s.mt.toFixed(1)} MT*

Container-wise:
${lines}

_Generated by Kraft Stuffing Log_`;
}

const TABS = ["Containers", "Bookings", "Documents", "P&L", "Activity"];

export default function VoyageDetailView({ app, voyageId }) {
  const { state, navigate, setActiveVoyage, updateVoyageEntry, archiveVoyageEntry, duplicateVoyage, addContainerEntry, exportXlsx, exportPdf, profilesById } = app;
  const { route } = useRouter();
  const tab = TABS.includes(route.params?.tab) ? route.params.tab : "Containers";
  const setTab = (t) => navigate("voyage-detail", { voyageId, tab: t });
  const [voyageExpenses, setVoyageExpenses] = useState(null);
  const { showToast } = useToast();
  const [selectedContainerId, setSelectedContainerId] = useState(null);
  const [editing, setEditing] = useState(false);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [online, setOnline] = useState(typeof navigator !== "undefined" ? navigator.onLine : true);
  const barRef = useRef(null);

  const voyage = state.voyages.find((v) => v.id === voyageId);

  useEffect(() => {
    if (voyageId) setActiveVoyage(voyageId);
  }, [voyageId, setActiveVoyage]);

  useEffect(() => {
    if (voyage) recordEntityVisit({ type: "voyage", id: voyage.id, label: `${voyage.vessel} · ${voyage.voyageNo}` });
  }, [voyage?.id]);

  useEffect(() => {
    if (tab !== "P&L" || !voyageId) return;
    let alive = true;
    fetchExpensesByVoyage(voyageId).then(({ data, error }) => {
      if (alive && !error) setVoyageExpenses((data || []).map(fromDbExpense));
    });
    return () => {
      alive = false;
    };
  }, [tab, voyageId]);

  useEffect(() => {
    const on = () => setOnline(true);
    const off = () => setOnline(false);
    window.addEventListener("online", on);
    window.addEventListener("offline", off);
    return () => {
      window.removeEventListener("online", on);
      window.removeEventListener("offline", off);
    };
  }, []);

  const s = voyage ? voyageStats(voyage) : { sealed: 0, total: 0, mt: 0, bags: 0 };
  const pct = s.total > 0 ? Math.round((s.sealed / s.total) * 100) : 0;

  useEffect(() => {
    if (barRef.current) {
      gsap.fromTo(barRef.current, { width: "0%" }, { width: `${pct}%`, duration: 0.6, ease: "power2.out" });
    }
  }, [pct, voyageId]);

  if (state.loading && !voyage) {
    return <ManifestSkeleton />;
  }
  if (!voyage) {
    return (
      <div style={{ minHeight: "100%", background: theme.color.canvas, padding: 40, fontFamily: theme.font.mono, color: theme.color.slate }}>
        Voyage not found.{" "}
        <button onClick={() => navigate("voyages")} style={{ color: theme.color.amber, background: "none", border: "none", cursor: "pointer" }}>
          ← Back to voyages
        </button>
      </div>
    );
  }

  const cycleStatus = () => {
    const idx = VOYAGE_STATUS_CYCLE.indexOf(voyage.status);
    const next = VOYAGE_STATUS_CYCLE[(idx + 1) % VOYAGE_STATUS_CYCLE.length];
    updateVoyageEntry(voyage.id, { status: next, archived: next === "ARCHIVED" });
    showToast(`Status → ${next}`, "info");
  };

  const onShare = async () => {
    const text = buildShareText(voyage);
    try {
      await navigator.clipboard.writeText(text);
      showToast("Copied to clipboard ✓", "success");
    } catch {
      showToast("Copy failed", "error");
    }
  };

  const onDuplicate = () => {
    const v = duplicateVoyage(voyage.id);
    if (v) {
      showToast(`Duplicated from ${voyage.voyageNo}`, "success");
      navigate("voyage-detail", { voyageId: v.id });
    }
  };

  const statusColor = VOYAGE_STATUS_COLORS[voyage.status] || theme.color.slate;
  const canDelete = voyage.status === "DRAFT" || voyage.status === "ARCHIVED";

  return (
    <div style={{ minHeight: "100%", background: theme.color.canvas, color: theme.color.ink }}>
    <div style={{ maxWidth: 1200, margin: "0 auto", padding: "14px 18px 40px" }}>
      {/* Breadcrumb */}
      <div style={{ fontFamily: theme.font.mono, fontSize: 11, color: theme.color.slate, marginBottom: 10 }}>
        <button
          onClick={() => navigate("voyages")}
          style={{ background: "none", border: "none", color: theme.color.slate, cursor: "pointer", fontFamily: theme.font.mono, fontSize: 11, padding: 0 }}
        >
          Voyages
        </button>{" "}
        / <span style={{ color: theme.color.inkSoft }}>{voyage.voyageNo}</span>
        <span style={{ marginLeft: 10, color: online ? theme.color.green : theme.color.slate }}>
          {online ? "● LIVE" : "○ SYNCING"}
        </span>
      </div>

      {/* Title row */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 12 }}>
        <div>
          <div style={{ fontFamily: theme.font.condensed, fontWeight: 800, fontSize: 30, color: theme.color.ink, lineHeight: 1 }}>
            {voyage.vessel}
          </div>
          <div style={{ fontFamily: theme.font.mono, fontSize: 12, color: theme.color.slate, marginTop: 4 }}>
            {voyage.voyageNo} · {voyage.pol} → {voyage.pod} · {voyage.date}
          </div>
        </div>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}>
          <button onClick={cycleStatus} style={{ ...iconBtn, color: statusColor, borderColor: statusColor }}>
            {voyage.status}
          </button>
          <button onClick={() => setEditing(true)} style={iconBtn}><Pencil size={14} /></button>
          <button onClick={onDuplicate} style={iconBtn}><Copy size={14} /></button>
          <button onClick={onShare} style={iconBtn}><Share2 size={14} /> Share</button>
          <ExportMenu onExportXlsx={() => exportXlsx(voyage)} onExportPdf={() => exportPdf(voyage)} />
          <DocumentGenerateMenu app={app} voyage={voyage} />
          {canDelete && (
            <button onClick={() => setConfirmingDelete(true)} style={{ ...iconBtn, color: theme.color.red, borderColor: "#f3c7c7" }}>
              <Trash2 size={14} />
            </button>
          )}
        </div>
      </div>

      {confirmingDelete && (
        <ConfirmDialog
          message={`Delete ${voyage.voyageNo}? This cannot be undone.`}
          confirmLabel="DELETE"
          onCancel={() => setConfirmingDelete(false)}
          onConfirm={() => {
            archiveVoyageEntry(voyage.id);
            setConfirmingDelete(false);
            showToast(`${voyage.voyageNo} archived`, "success");
            navigate("voyages");
          }}
        />
      )}

      {/* Status / progress bar */}
      <div style={{ marginTop: 16, background: theme.color.surface, border: `1px solid ${theme.color.border}`, borderRadius: theme.radius.card, boxShadow: theme.shadow.card, padding: "12px 16px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", fontFamily: theme.font.mono, fontSize: 11, color: theme.color.slate }}>
          <span>{s.sealed} of {s.total} containers sealed</span>
          <span style={{ color: theme.color.amberText }}>{pct}%</span>
        </div>
        <div style={{ height: 8, background: theme.color.surfaceMuted, borderRadius: 4, marginTop: 8, overflow: "hidden" }}>
          <div ref={barRef} style={{ height: "100%", width: `${pct}%`, background: theme.color.amber, borderRadius: 4 }} />
        </div>
      </div>

      {/* Voyage P&L strip (Phase 6) */}
      <VoyagePnlStrip
        voyageId={voyage.id}
        onAddEntry={() => navigate("expenses", { addForVoyage: voyage.id })}
      />

      {/* Tabs */}
      <div style={{ display: "flex", gap: 4, marginTop: 16, borderBottom: `1px solid ${theme.color.border}`, overflowX: "auto" }}>
        {TABS.map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            style={{
              background: "none",
              border: "none",
              borderBottom: `2px solid ${tab === t ? theme.color.amber : "transparent"}`,
              color: tab === t ? theme.color.ink : theme.color.slate,
              fontFamily: theme.font.condensed,
              fontWeight: 700,
              fontSize: 14,
              letterSpacing: "0.05em",
              textTransform: "uppercase",
              padding: "9px 14px",
              cursor: "pointer",
              whiteSpace: "nowrap",
            }}
          >
            {t}
          </button>
        ))}
      </div>

      {tab === "Bookings" && <BookingsView app={app} voyage={voyage} />}
      {tab === "Documents" && <DocumentsView app={app} voyageId={voyage.id} />}
      {tab === "Activity" && <ActivityFeedView app={app} voyageId={voyage.id} embedded />}
      {tab === "P&L" && (
        <div style={{ marginTop: 16 }}>
          {voyageExpenses === null ? (
            <div style={{ fontFamily: theme.font.mono, fontSize: 12, color: theme.color.slate }}>Loading…</div>
          ) : (
            <ExpenseListView
              expenses={voyageExpenses}
              onSelect={() => navigate("expenses", { voyageFilter: voyage.id })}
            />
          )}
        </div>
      )}

      {/* Manifest */}
      {tab === "Containers" && (
      <div style={{ marginTop: 16 }}>
        {voyage.containers.length === 0 ? (
          <div style={{ textAlign: "center", padding: "50px 20px" }}>
            <div style={{ fontFamily: theme.font.condensed, fontWeight: 800, fontSize: 24, color: theme.color.slateFaint }}>
              NO CONTAINERS — tap + to add one
            </div>
            <button
              onClick={() => addContainerEntry(voyage.id)}
              style={{ marginTop: 16, ...iconBtn, color: theme.color.amber, borderColor: theme.color.amber }}
            >
              <Plus size={14} /> Add container
            </button>
          </div>
        ) : (
          <>
            <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 8 }}>
              <button
                onClick={() => addContainerEntry(voyage.id)}
                style={{ ...iconBtn, color: theme.color.amber, borderColor: theme.color.amber }}
              >
                <Plus size={14} /> Add container
              </button>
            </div>
            <ManifestTable
              containers={voyage.containers}
              voyageNo={voyage.voyageNo}
              selectedContainerId={selectedContainerId}
              onSelectContainer={setSelectedContainerId}
              onOpenLog={(cid) => navigate("container-log", { containerId: cid })}
            />
          </>
        )}
      </div>
      )}

      {selectedContainerId && (() => {
        const c = voyage.containers.find((x) => x.id === selectedContainerId);
        return c ? (
          <ContainerInfoOverlay
            container={c}
            onClose={() => setSelectedContainerId(null)}
            onSelectLine={() => navigate("container-log", { containerId: c.id })}
            profilesById={profilesById}
            app={app}
            voyage={voyage}
          />
        ) : null;
      })()}

      {editing && (
        <CreateVoyageModal
          voyage={voyage}
          onClose={() => setEditing(false)}
          onSubmit={(patch) => {
            updateVoyageEntry(voyage.id, patch);
            setEditing(false);
            showToast("Voyage updated", "success");
          }}
        />
      )}
    </div>
    </div>
  );
}
